FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake pkg-config libtool libsdl2-dev

COPY . /repo
WORKDIR /repo
RUN autoreconf -if
RUN ./configure --disable-sherlock
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/libde265/.libs
